### ISSUE TITLE
Don't disable Bitcoin Core wallet UI if there is an existing BC wallet

### ISSUE THREAD

**Issue by PierreRochard** [lightning-power-users/node-launcher#152]
Currently, the Node Launcher sets `disablewallet=1` if `bitcoin.conf` so that new users don't accidentally send BTC to a Bitcoin Core wallet instead of to an LND wallet.

While this is the desired default behavior, there are users who have previously been using a Bitcoin Core wallet and would like to continue to have access to it. For them, `disablewallet=0` should be set.

**Comment by luke-jr** [comment]
As long as you're launching it, why not just pass all the settings you want to override on the command line instead of a config file? That way normal Bitcoin Core usage is unaffected.

**Comment by PierreRochard** [comment]
Personally, with the way I use the Node Launcher, I do want this project to affect my normal Bitcoin Core usage in positive ways and not affect it in negative ways. 

I've put in a fix that looks for wallet files in `datadir`, `datadir/wallets`, and `walletdir`, if wallet file(s) are present then `disablewallet=0`
