### ISSUE TITLE
Javascript Error Message when opening Zap wallet using launcher v5.4.1

### ISSUE THREAD

**Issue by jchello** [lightning-power-users/node-launcher#154]
See attached every time I click open Zap. Zap proceeds to then open successfully, no other apparent issues. Could this be a local problem? Mac OSX 10.13.6
![screen shot 2019-02-02 at 1 16 06 pm](https://user-images.githubusercontent.com/9296962/52168251-772c3000-26ed-11e9-9fc6-4b41445f9c5e.png)

**Comment by PierreRochard** [comment]
Zap is fixing this in the next release: https://github.com/LN-Zap/zap-desktop/issues/1442
