### ISSUE TITLE
wild bug zap qr for node launcher 

### ISSUE THREAD

**Issue by luvarado** [lightning-power-users/node-launcher#165]
Wild bug appears! 
Please copy this text and open an issue on GitHub.
Node Launcher version 5.5.0

Error information:

'Lnd' object has no attribute 'tlsextraip'
File "node_launcher\gui\network_buttons\zap_layout.py", line 60, in show_zap_qrcode

**Comment by manecosta** [comment]
This functionality was broken with some previous changes. Also it was not implemented in an ideal way. I already proposed #167 to disable it for now until a good solution is found.

**Comment by PierreRochard** [comment]
Thank you @manecosta !

Sorry @luvarado, we'll get this feature back in ASAP

**Comment by luvarado** [comment]
Thank you
@PierreRochard 
@manecosta
