### ISSUE TITLE
Cannot Change Bitcoin Directory Node Launcher Looks For

### ISSUE THREAD

**Issue by shane1900** [lightning-power-users/node-launcher#166]
Hi,

Everything was working fine until I moved the Bitcoin chain directory.  Conf has been updated and Bitcoin Core works fine but when I open Node Launcher it looks at the old directory.  How can I change this?

Thank you

**Comment by PierreRochard** [comment]
That's very odd, it should be reading `datadir` from the configuration file. Does the preferences window `datadir` match up with what you put in the conf file?

**Comment by shane1900** [comment]
Yes it does.  I searched and updated all bitcoin config files and even deleted tmp and Lnd and Node Launcher to no avail.

Maybe a Windows 10 NAS mounting drive issue so I just went back to the old directory.

But now working with a new error :(  After downloading the current Node Launcher and recovering my wallet and being caught up to current height I have a ton of these errors.


![screen shot 2019-02-06 at 12 05 49 pm](https://user-images.githubusercontent.com/13156874/52366694-9d144600-2a07-11e9-8e9a-136e147754da.png)

**Comment by PierreRochard** [comment]
Hmm I don't know if Bitcoin Core can work with `datadir` on a NAS... Maybe someone will have the same issue and comment here. I don't have a NAS to test with

I remember seeing those warnings as well.

**Comment by PierreRochard** [comment]
Also, did you have channels open? You'll have to get the people on the other end to force close the channel for the recovery to work

**Comment by shane1900** [comment]
That went away after closing the app.

All is running well but in Zap my BTC and channels are not showing, any hints?  Using the same 24 words as before and all settings are the same.

**Comment by shane1900** [comment]
If my Zap's deposit address is different than the address I first made a deposit is that I sign I might be using the wrong recovery phrase?

I tried putting my 24 words in https://iancoleman.io/bip39/ and received invalid mnemonic.

**Comment by PierreRochard** [comment]
That's really a question for the Zap project, I don't use the desktop app and I'm thinking of removing it from the Node Launcher all together at this point
