### ISSUE TITLE
🤬 Wild Bug, now launcher won't run, lnd.conf missing parts now

### ISSUE THREAD

**Issue by manakill** [lightning-power-users/node-launcher#178]
v 5.5.1 - running great for days, and I just I went to settings to change node color and name. I tried using a special character to get the lightning bolt emoji next to my alias. It threw an error and crashed, I don't have that error but the char I used was ΓÜí

Now when launching it says:
Error information:

'list' object has no attribute 'split'
File "run.py", line 12, in File "node_launcher\gui\main_widget.py", line 44, in __init__ File "node_launcher\gui\network_buttons\network_widget.py", line 19, in __init__ File "node_launcher\node_set\node_set.py", line 32, in __init__ File "node_launcher\node_set\lnd.py", line 76, in __init__ 

I tried v 6.0 and that just crashes w/o any error message popup, so I went back to 5.5.1 and get the same error as above

I looked at lnd.conf and there is now stuff missing, no rpc or alias, half the file is gone.

**Comment by manakill** [comment]
tls strings in lnd.conf are gone too...

**Comment by manakill** [comment]
Trying to recover and it says seed doesn't match.. wtfh

**Comment by manakill** [comment]
I got the node launcher to run once by doing a fresh install and copying files and opening seed. Was running fine, shut it down to backup files, and now I get the same error as above

**Comment by PierreRochard** [comment]
Thanks for the bug report! Taking a look now

**Comment by PierreRochard** [comment]
Awesome, figured it out, fix will be in the next release! It's because you have multiple `listen` items in your config (which is allowed!) but I wasn't expecting that
