### ISSUE TITLE
Can send but not receive

### ISSUE THREAD

**Issue by DerHuette** [lightning-power-users/node-launcher#206]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [X] support request

I followed your tutorial on medium.com ("Easiest Bitcoin Lightning Guide") and everything went well. Now I can open a channel and send with the Joule Extension.  What does not work is receiving (tried with bluewallet on my android phone and with lightning-roulette.com). The error code is something like "unable to route payment to destination: TemporaryChannelFailure".

Do I have to do some more configuration for that? Could it be the problem that I don't have a static IP address? Is there a solution for that?

Thank you in advance!

Just forgot: yes, I do forward TCP port 9735 from my router to the machine running lnd.

* **Please tell us about your environment:**

  - Operating System: [ Windows 10 ]

**Comment by HelgeHunding** [comment]
Do you have enough inbound capacity on your node? You get that when sending payments or when someone is opening a channel to you. If not, you might want to try with a service like https://www.bitrefill.com/thor-lightning-network-channels or get someone else to open a channel to you.

**Comment by hkrugersa** [comment]
Some good advice on bootstrapping channels can be found at https://wiki.ion.radar.tech/tutorials/troubleshooting/bootstrapping-channels and https://github.com/rootzoll/raspiblitz/issues/395

**Comment by PierreRochard** [comment]
You can also try https://lightningpowerusers.com/home/
