### ISSUE TITLE
Linux Install Support 

### ISSUE THREAD

**Issue by qwaa702** [lightning-power-users/node-launcher#207]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] support request

* **What is the current behavior?**
Terminal is outputting "SyntaxError: invalid syntax" when executing the python setup.py develop and python run.py commands.

* **If the current behavior is a bug, please provide the steps to reproduce**

* **What is the expected behavior?**
To install and compile the source code so a user can integrate the program on linux OS.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
Ubuntu 18.10, Linux OS
  - Operating System: [ Windows | macOS | Linux ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
     I pretty much follow the developer instructions to install via linux terminal and I run into this error. I am relatively new to linux so I don't know how to troubleshoot the issue. I would love to help if possible. 
![screenshot from 2019-02-26 17-22-45](https://user-images.githubusercontent.com/20012969/53458496-391fe480-39eb-11e9-8ed0-f8dc42105955.png)

**Comment by PierreRochard** [comment]
You must be using Python < 3.7

Python 3.7 is required

This might be helpful: https://jcutrer.com/linux/upgrade-python37-ubuntu1810
