### ISSUE TITLE
Got my node up in 5.6 but still lost...

### ISSUE THREAD

**Issue by jocarp** [lightning-power-users/node-launcher#209]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [ x] support request

* **What is the current behavior?**

My node is up and running but i don't really know how to interface with it. I have  a few bitcoin in a hot wallet on my phone but don't get how to lock it up better or find it on ledger or move it some around and get it in my LND wallet..

LND Wallet- got as far as print mnemonic word list, then totally stumped. When I go to create wallet, up pops the terminal and I get even more confused as I don't have much experience on that. Here is the last try and output there:

 "Last login: Sat Mar  2 11:21:20 on ttys000
/var/folders/cx/hzgkn_7n45n2wcpz78b5xhgm0000gn/T/tmp_i6ukv_d-lnd.command ; exit;
Johns-iMac-7:~ johncarpenter$ /var/folders/cx/hzgkn_7n45n2wcpz78b5xhgm0000gn/T/tmp_i6ukv_d-lnd.command ; exit;
2019-03-02 11:22:46.466 [INF] LTND: Version: 0.5.2-beta commit=v0.5.2-beta, build=production, logging=default
2019-03-02 11:22:46.467 [INF] LTND: Active chain: Bitcoin (network=mainnet)
2019-03-02 11:22:46.467 [INF] CHDB: Checking for schema update: latest_version=7, db_version=7
2019-03-02 11:22:46.476 [INF] RPCS: password RPC server listening on 127.0.0.1:10009
2019-03-02 11:22:46.477 [INF] RPCS: password gRPC proxy started at 127.0.0.1:8080
2019-03-02 11:22:46.477 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create a wallet, `lncli unlock` to unlock an existing wallet, or `lncli changepassword` to change the password of an existing wallet and unlock it."

ok so where am I supposed to go from here please? 

I want to be able to view the ledger, open my LND wallet, move BTC in and out, open & close channels, send BTC over LND etc etc. I have read this tutorial over and over and feel pretty stupid not being able to sort this out yet.

Is there a good resource for ignorant beginners who want to adopt like me but aren't quite up to speed yet? Please let me know and thank you!!

* **If the current behavior is a bug, please provide the steps to reproduce**

* **What is the expected behavior?**

Basic Functionality

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

  - Operating System: [ macOS ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by PierreRochard** [comment]
Hi @jocarp! The new version of the Node Launcher is a lot more user friendly!

https://github.com/lightning-power-users/node-launcher/releases

I've also updated the guide to make it simpler:
https://medium.com/lightning-power-users/windows-macos-lightning-network-284bd5034340

Happy to reopen this issue and make more improvements if anything isn't clear!

**Comment by jocarp** [comment]
Thanks Pierre! I appreciate your help. Hope to catch you Friday at the Boltathon!!

Sent from my iPhone

On Apr 3, 2019, at 12:29 PM, Pierre Rochard <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @jocarp<https://github.com/jocarp>! The new version of the Node Launcher is a lot more user friendly!

https://github.com/lightning-power-users/node-launcher/releases

I've also updated the guide to make it simpler:
https://medium.com/lightning-power-users/windows-macos-lightning-network-284bd5034340

Happy to reopen this issue and make more improvements if anything isn't clear!
