### ISSUE TITLE
Can't fund Zap wallet

### ISSUE THREAD

**Issue by galenmoore** [lightning-power-users/node-launcher#210]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x ] support request

* **What is the current behavior?**
I followed the instructions in the Zap Desktop send-a-payment guide (https://medium.com/lightning-power-users/send-a-lightning-payment-with-zap-desktop-17b74b65b9b8), including setting up BTC/LN nodes and setting up Zap Desktop. All went basically as described, until I attempted to send a small amount of BTC from my Ledger wallet to the BTC address provided in the Zap Desktop app. That transaction took place over one hour ago and my block explorer now shows five confirmations. It's still not showing up in the Zap Desktop wallet. 

Any suggestions would be much appreciated. 

* **If the current behavior is a bug, please provide the steps to reproduce**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

  - Operating System: [ Windows | macOS | Linux ] macOS

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by PierreRochard** [comment]
I don't use Zap, I only use Joule, maybe it shows up in Joule? https://medium.com/lightning-power-users/bitcoin-lightning-joule-chrome-extension-ac149bb05cb9

**Comment by galenmoore** [comment]
I was hoping to avoid the process there, which looks a little more involved than the Zap installation, but I can try it. (First I will cross-post this to Zap's support forum, if I can find it.) I guess Joule will pull the same BTC address from the Node launcher?

**Comment by PierreRochard** [comment]
Yes, though technically both Zap and Joule are communicating with the LND Wallet directly, not through the Node Launcher per se. 

I promise Joule is fantastic!

**Comment by galenmoore** [comment]
Looks like it's a problem with node syncing. I don't think I was communicating with a full Bitcoin node. So I need to go back and resync, to fix it, I guess.

**Comment by galenmoore** [comment]
...still couldn't make it work with Zap, but Joule is working fine. So I'll just use that for now. Thanks.
