### ISSUE TITLE
Node Launcher starting a fresh sync of blockchain

### ISSUE THREAD

**Issue by Bucwolfser** [lightning-power-users/node-launcher#214]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request

* **What is the current behavior?**
I've just downloaded a fresh copy of the Bitcoin Blockchain in Bitcoin Core. I installed the newest release of Node Launcher, hit launch Bitcoin, Bitcoin Core opens and it begins downloading the blockchain from scratch.

* **If the current behavior is a bug, please provide the steps to reproduce**
Install and sync bitcoin core, close it.
Open node launcher, launch bitcoin.

* **What is the expected behavior?**
Bitcoin will begin synchronizing with network, downloading the blockchain from start.

* **What is the motivation / use case for changing the behavior?**
Remove duplicate blockchain downloads

* **Please tell us about your environment:**
Windows 10 10.0.17763 Build 17763 - intel 4690k, 16gb 
  - Operating System: [ Windows | macOS | Linux ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
[Joe Rodgers - debug.txt](https://github.com/lightning-power-users/node-launcher/files/2971605/Joe.Rodgers.-.debug.txt)

**Comment by PierreRochard** [comment]
Yikes! Thanks for reporting this issue @Bucwolfser, I've made a new release that improved the Data Directory handling logic and logging. I'll reopen this issue if you experience this problem again
