### ISSUE TITLE
LND wallet buttons permanetly greyed out

### ISSUE THREAD

**Issue by masterexit** [lightning-power-users/node-launcher#215]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [*] support request

* **What is the current behavior?**
LND wallet buttons 'unlock', create' & 'recover' have never been available to me. LND & Bitcoin wallet synced and working correctly.
What did I do wrong?

* **If the current behavior is a bug, please provide the steps to reproduce**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

  - Operating System: [ |macOS  ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by PierreRochard** [comment]
Have you used LND or Bitcoin on this computer before using the Node Launcher?

**Comment by PierreRochard** [comment]
Try out the new release! https://github.com/lightning-power-users/node-launcher/releases
