### ISSUE TITLE
Zap doesn't show Channel state 

### ISSUE THREAD

**Issue by luvarado** [lightning-power-users/node-launcher#216]
* **I'm submitting a ...**
  - [ x] bug report
  - [ ] feature request
  - [ ] support request

* **What is the current behavior?**
Zap will not continue to show channel connections after the closure and the reopening of it. 

* **If the current behavior is a bug, please provide the steps to reproduce**
When I first run node launcher, the zap wallet connects and shows the channel connections.
If I close out zap and reopen zap the current channel state is no longer present. 

* **What is the expected behavior?**
I have to eventually shut lnd down and re-launch it for zap to show the channels. 

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

  - Operating System: [ Windows ]

**Comment by PierreRochard** [comment]
I recommend using Joule instead of Zap, it's worked better for me https://medium.com/lightning-power-users/bitcoin-lightning-joule-chrome-extension-ac149bb05cb9
