### ISSUE TITLE
Open a New Channel unavail after BTC deposit

### ISSUE THREAD

**Issue by Zeno78** [lightning-power-users/node-launcher#217]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [ X ] support request

* **What is the current behavior?**
Cannot open channel after sending BTC to address to fund network.

* **If the current behavior is a bug, please provide the steps to reproduce**

* **What is the expected behavior?**
Go to open channel and enter 500000 sat and it gives a error saying Amount exceeds maximum (0 sats) Ther is 1451273 sats avail.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

  - Operating System: [ Windows | macOS | Linux ]
Windows 10 Pro 64 bit
* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by Zeno78** [comment]
Failed to open channel
amount pushed to remote peer for initial state must be below the local funding amount

**Comment by Zeno78** [comment]
Failed to open channel
not enough witness outputs to create funding transaction, need 0.01452328 BTC only have 0.01451273 BTC available

**Comment by Zeno78** [comment]
so do I need to choose another connection info?

**Comment by Zeno78** [comment]
Failed to open channel
reservation timed out waiting for peer (peerID:&{0x1a565a0 22601551300326490230116595119525826801062252783150288400370681939615436389500 47196481506497706782152069745981528392642650213706985330650790898027560459857}, chanID:228fb2a4f0203bc350be5b7e32d51c6a4e4b9a7e7326febbbc1a35d951d58b29)

**Comment by PierreRochard** [comment]
Yikes, I've had that error as well

https://github.com/lightningnetwork/lnd/issues/2421

**Comment by PierreRochard** [comment]
Who were you trying to open the channel with?

**Comment by Zeno78** [comment]
you: 0331f80652fb840239df8dc99205792bba2e559a05469915804c08420230e23c7c@mainnet.node.lightningpowerusers.com:9735

**Comment by Zeno78** [comment]
following the medium article

**Comment by Zeno78** [comment]
well I reduced the amount a bit further to 1400000 sats and it open the channel... weird... SO I guess it up and running now.
