### ISSUE TITLE
my and node was off for Monday and tuesday and I can't get the node-launcher to connect to the lightning network. the wallet can't find the host and launch and gets me a msg referring to roast beff GitHub...

### ISSUE THREAD

**Issue by tekeefe13** [lightning-power-users/node-launcher#221]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [ ] support request

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

  - Operating System: [ Windows | macOS | Linux ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by tekeefe13** [comment]
i am using an old iMac with upgraded ram and ssd's .

**Comment by HelgeHunding** [comment]
What is the message? Is your bitcoin core node fully synced (it's no longer giving you a message that it syncs)?

**Comment by tekeefe13** [comment]
I will get back tomorrow and send you the message. It is not synching. Thanks  Tim

**Comment by PierreRochard** [comment]
I'll reopen when we have the message
