### ISSUE TITLE
Node-launcher v6.0 fails to launch on Win10

### ISSUE THREAD

**Issue by editor-Ajian** [lightning-power-users/node-launcher#232]
* **I'm submitting a ...**
  - [ X ] bug report
  - [ ] feature request
  - [ ] support request

* **What is the current behavior?**

When I execute node launcher, it pops a window saying that "cannot execute script run"
Then I download the source code, run the run.py in my python interpreter, and one-by-one install those dependencies correctly, then make sure that I can execute run.py successfully. 
However, I still cannot launch the node, neither the setup.py, (error information is "error: no commands supplied"), nor the node-launcher.exe.

* **If the current behavior is a bug, please provide the steps to reproduce**

I think that it is a bug. Node-launcher fail to run regarding that I have installed those requirements.

* **What is the expected behavior?**

Node-launcher.exe or setup.py is able to run.

* **Please tell us about your environment:**

  - Operating System:  Windows 64 bit
  - Python 3.7
  - Pip last version

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by HelgeHunding** [comment]
I got this error:

``` 
File "C:\Users\User1\Code\node-launcher\node_launcher\gui\system_tray_widgets\bitcoind_output_widget.py", line 3, in <module>
    import humanize
ModuleNotFoundError: No module named 'humanize'
```
and I guess that's your issue to? I think `humanize` is missing from requirments.txt.

If you have Python and Pip installed, run:

`pip install humanize` 

and then run the .exe file again (or run.py)

**Comment by editor-Ajian** [comment]
Thanks for your response.
 
But I actually use pip install humanize module.

To be honest, it was included in the requirements.txt. 

So it is not the case.

**Comment by HelgeHunding** [comment]
Ahh, yeah sorry you're right. My bad! 

I realized that the .exe doesn't work on my machine either. But I can run it by pulling the latest changes and using `python run.py`.

This is the error I got when running the debug.exe-file:

![image](https://user-images.githubusercontent.com/46749239/55392886-a9121500-552b-11e9-9090-1bee2beb9019.png)

**Comment by PierreRochard** [comment]
I'm having the same error on windows 10, trying to figure out how to fix it with pyinstaller

**Comment by PierreRochard** [comment]
Try out the latest release and let me know what you think! 

https://github.com/lightning-power-users/node-launcher/releases

**Comment by HelgeHunding** [comment]
Nice! Works on my end.
