### ISSUE TITLE
Error: -daemon is not supported on this operating system.

### ISSUE THREAD

**Issue by brandoncollins7** [lightning-power-users/node-launcher#234]
* **I'm submitting a ...**
  - [* ] bug report

* **What is the current behavior?**
bitcoin node fails to start on Windows 10 Pro

* **If the current behavior is a bug, please provide the steps to reproduce**
Launch the app

* **What is the expected behavior?**
Node should start syncing

* **Please tell us about your environment:**

Windows 10 Pro

**Comment by PierreRochard** [comment]
Open your bitcoin.conf file and delete daemon=1 from there

https://github.com/bitcoin/bitcoin/issues/13121
