### ISSUE TITLE
pyi_rth_qt5plugins - script error

### ISSUE THREAD

**Issue by dsholbrook** [lightning-power-users/node-launcher#244]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **What is the current behavior?**
Error message upon launching Node Launcher 6.0.1 -
Failed to execute script pyi_rth_qt5plugins

* **If the current behavior is a bug, please provide the steps to reproduce**
Launching Node Launcher 6.0.1.

* **What is the expected behavior?**
Node Launcher should start.

* **What is the motivation / use case for changing the behavior?**
Version 5.6.0 works well. Using older version for now.

* **Please tell us about your environment:**

  - Operating System: [ Windows 10 Professional]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by PierreRochard** [comment]
Hi @dsholbrook! I just uploaded a debug build, mind giving it a try? https://github.com/lightning-power-users/node-launcher/releases

**Comment by dsholbrook** [comment]
Done. Command window opened as normal, then closed, but Node Launcher did not start. If I can share any debug logs, just point me to the path where to look.

**Comment by PierreRochard** [comment]
Does it look something like this? 

![image](https://user-images.githubusercontent.com/6299681/55577822-70686c00-56e2-11e9-955a-5d324a95b044.png)

**Comment by dsholbrook** [comment]
Yes. Attaching screen capture.
![2019-04-04 13_33_37-](https://user-images.githubusercontent.com/49285902/55579780-a7d51980-56de-11e9-9f8b-3ee3f25b896b.jpg)

**Comment by wiseoldram** [comment]
+1 for experiencing this same result

**Comment by dsholbrook** [comment]
Same error with the latest release - 6.0.2.

**Comment by dython6** [comment]
same with "6.0.2 Bump LND to v0.6-beta-rc3" i even tried previous versions and they gave the same result failed to execute script pyi_rth_qt5plugins

**Comment by dsholbrook** [comment]
Release 6.0.3, same error also. I'm still on release 5.6.0, which works. Maybe dython6 above has a good clue; could be a file compression issue?

**Comment by dsholbrook** [comment]
Release 6.0.4 same error. My path is: c:\data\bitcoin for your node launcher.

**Comment by GamerOfChains** [comment]
I'm still getting it too.

**Comment by dsholbrook** [comment]
Pierre I'm going to close this issue. I'm rocking now. Like the new updates! After installing this & rebooting (as you recommended for the ver 6.0.5 release) -
https://www.microsoft.com/en-us/download/details.aspx?id=48145

- it fixed this problem.

** NOTE: I had to rename my old bitcoin.conf file to bitcoin.old to get it to work. At least one line in my old 5.6.0 version was choking up the 'bitcoind' process.
