### ISSUE TITLE
GUI not loading after update

### ISSUE THREAD

**Issue by stacy-c** [lightning-power-users/node-launcher#245]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [ x ] support request

* **What is the current behavior?**
On macOS High Sierra 10.13.6 I replaced the Node Launcher app with the latest from 4/2/19. Not sure if I did that correctly - I just shut down NL, deleted the app, and copied the new one into the Applications folder and started it. Activity Monitor app shows Node Launcher running, but the GUI is not visible as it was before. Also, I don't know if this is related but the ZapDesktop is stuck at “Loading” so I wonder if I have lost my LN funds? I had one channel open with Lightning Power Users. Thanks!

* **If the current behavior is a bug, please provide the steps to reproduce**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

Want to restore Node Launcher / LN back to previous operating status.

* **Please tell us about your environment:**

  - Operating System: [ macOS 10.13.6 ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by PierreRochard** [comment]
I'm sure you didn't lose LN funds! 

Is there a Bitcoin icon in your system tray at the top right? 
![image](https://user-images.githubusercontent.com/6299681/55598872-f2788500-5722-11e9-8ea9-a3dbb07de8ab.png)

**Comment by stacy-c** [comment]
Yes, this is my menu.

![Screen Shot 2019-04-04 at 10 20 57 PM](https://user-images.githubusercontent.com/49287259/55601791-286c3800-5728-11e9-8011-a4ba9776fb76.png)

**Comment by stacy-c** [comment]
FYI ... Bitcoin output:

Error: Cannot obtain a lock on data directory /Volumes/T5/Bitcoin. Bitcoin Core is probably already running.
2019-04-04T13:16:49Z Bitcoin Core version v0.17.1 (release build)
2019-04-04T13:16:49Z InitParameterInteraction: parameter interaction: -whitelistforcerelay=1 -> setting -whitelistrelay=1
2019-04-04T13:16:49Z Assuming ancestors of block 0000000000000000002e63058c023a9a1de233554f28c7b21380b6c9003f36a8 have valid signatures.
2019-04-04T13:16:49Z Setting nMinimumChainWork=0000000000000000000000000000000000000000028822fef1c230963535a90d
2019-04-04T13:16:49Z Using the 'sse4(1way),sse41(4way)' SHA256 implementation
2019-04-04T13:16:49Z Error: Cannot obtain a lock on data directory /Volumes/T5/Bitcoin. Bitcoin Core is probably already running.

**Comment by stacy-c** [comment]
Restarted the machine today, things look better, Zap Desktop has started and shows connection to LightningPowerUsers.com. Thanks for your help Pierre.

<img width="218" alt="Screen Shot 2019-04-05 at 8 31 22 AM" src="https://user-images.githubusercontent.com/49287259/55631390-85460d80-577d-11e9-9478-b0e2bad8f72e.png">

**Comment by PierreRochard** [comment]
`Cannot obtain a lock on data directory /Volumes/T5/Bitcoin. Bitcoin Core is probably already running.`

Yup Bitcoin Core has to be stopped before starting the Node Launcher.

Glad you got it working!
