### ISSUE TITLE
Wild bug appears!

### ISSUE THREAD

**Issue by HurlyDesousa** [lightning-power-users/node-launcher#248]
Wild bug appears! 
Please copy this text and open an issue on GitHub.
Node Launcher version 6.0.2

Error information:

[WinError 3] The system cannot find the path specified: 'H:\\Bitcoin\\testnet3'
File "run.py", line 22, in File "node_launcher\gui\application.py", line 15, in __init__ File "node_launcher\node_set\node_set.py", line 29, in __init__ File "node_launcher\node_set\bitcoin.py", line 54, in __init__ File "node_launcher\node_set\bitcoin.py", line 128, in get_wallet_paths

**Comment by HurlyDesousa** [comment]
I'm a noob so i have no idea what it means. But when i run the new version of Windows.Node.Launcher.exe the alert pops up almost instantly.

**Comment by HurlyDesousa** [comment]
Where can i set the directory, of the bitcoin chain?

**Comment by HurlyDesousa** [comment]
ah, fixed it!
In the bitcoin.conf file i canged the `datadir=C:\Bitcoin`  line to the correct directory.

**Comment by PierreRochard** [comment]
Great, thanks for the bug report!

**Comment by watwood** [comment]
Wild bug appears!  Please copy this text and open an issue on GitHub. Node Launcher version 6.0.2  Error information:  'LndOutputWidget' object has no attribute 'error_message' File "node_launcher/gui/system_tray_widgets/lnd_output_widget.py", line 151, in handle_unlock_wallet File "node_launcher/gui/system_tray_widgets/lnd_output_widget.py", line 103, in generate_seed 

I'm just doing as instructed in the above text. Don't expect me to know what the heck I'm doing. Just following Pierre's "yes they were simple instructions" until this :-)

**Comment by runjam1** [comment]
'NoneType' object has no attribute 'split'
File "node_launcher\node_set\lnd.py", line 192, in config_file_changed

**Comment by runjam1** [comment]
![Screenshot (14)](https://user-images.githubusercontent.com/42794700/55855807-57feb400-5b1d-11e9-96be-a15a9f351fe7.png)

**Comment by runjam1** [comment]
![Screenshot (15)](https://user-images.githubusercontent.com/42794700/55856075-0f93c600-5b1e-11e9-8250-12c920a889bf.png)

**Comment by PierreRochard** [comment]
Thanks for the bug report @runjam1 ! This will be fixed in the next release
