### ISSUE TITLE
bug 'LndOutputWidget' object has no attribute 'error_message'

### ISSUE THREAD

**Issue by Natelynch** [lightning-power-users/node-launcher#251]
* **I'm submitting a ...**
  - [ x] bug report
  - [ ] feature request
  - [ ] support request

* **What is the current behavior?**
fail on launch

* **If the current behavior is a bug, please provide the steps to reproduce**

open node launcher

* **What is the expected behavior?**

it runs

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
macosx all current
  - Operating System: [ Windows | macOS | Linux ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Wild bug appears! 
Please copy this text and open an issue on GitHub.
Node Launcher version 6.0.2

Error information:

'LndOutputWidget' object has no attribute 'error_message'
File "node_launcher/gui/system_tray_widgets/lnd_output_widget.py", line 151, in handle_unlock_wallet File "node_launcher/gui/system_tray_widgets/lnd_output_widget.py", line 103, in generate_seed

**Comment by PierreRochard** [comment]
Thank you for reporting this bug! It'll be fixed in the next release and we'll find out what the error message was supposed to be...
