### ISSUE TITLE
Bitcoin Synced, LND never finishes

### ISSUE THREAD

**Issue by jbhoz** [lightning-power-users/node-launcher#253]
Running windows 10, laptop had fully synced  "bitcoin" but LND continues to say syncing with no ETA. Initially had a 3min ETA on LND but never finished. In open log says "failed handshake". Went through options trying to see if I had missed something and selected "enable bitcoin wallet" "enable testnet". Now failing to open launcher fatal error "failed to execute script run". Ran Debug -

[WinError 3] The system cannot find the path specified: 'C:\\Users\\James H\\AppData\\Roaming\\Bitcoin\\testnet3'
File "run.py", line 22, in File "node_launcher\gui\application.py", line 15, in __init__ File "node_launcher\node_set\node_set.py", line 29, in __init__ File "node_launcher\node_set\bitcoin.py", line 54, in __init__ File "node_launcher\node_set\bitcoin.py", line 128, in get_wallet_paths 

I broke it!! sorry... please help =)

**Comment by PierreRochard** [comment]
open your bitcoin.conf file in `%appdata%/Bitcoin` and remove `\testnet3` from the `datadir` line, and set testnet to 0

Please send a screenshot of the LND log so we can debug that!

**Comment by Jameshill89** [comment]
I set testnet to 0 in %appdata/bitcoin/bitcoin.conf and it let me re-open the launcher.exe. LND Synced now! Thanks Pierre!

**Comment by PierreRochard** [comment]
Awesome, congrats @Jameshill89 !
