### ISSUE TITLE
Wild bug appeared

### ISSUE THREAD

**Issue by ando999** [lightning-power-users/node-launcher#254]
* **I'm submitting a ...**
  - [ x] bug report
  - [ ] feature request
  - [ ] support request

* **What is the current behavior?**

Node launcher does not get past startup

* **If the current behavior is a bug, please provide the steps to reproduce**

Start Node Launcher app

* **What is the expected behavior?**

That it does not crash

* **What is the motivation / use case for changing the behavior?**

It has been like this from the beginning

* **Please tell us about your environment:**

  - Operating System: [ macOS ]

* **Other information** (e.g. det
<img width="419" alt="Screenshot 2019-04-07 at 17 01 52" src="https://user-images.githubusercontent.com/1786511/55685627-af9ff280-5958-11e9-909a-6206fe30bd45.png">
ailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

If you please let me know where I can get the logs from, I will send them to you. When the error message comes and I click OK, the whole application crashes including the logs that I watching on the screen

**Comment by Bombasarkadian** [comment]
The same error happens to me on macOS 10.14.5. However, everything works alright until the mac goes to sleep. After waking up there are tens of those messages and closing first one causes node launcher to quit.

**Comment by freehodl** [comment]
I had the same error. @PierreRochard it looks like the change variable defined on line 65 in lnd_output_widget.py can be 0 if lnd stops and restarts without the height changing. This throws the division by zero error on line 68 when total_left is divided by change. I added a line that fixes it so that the script to calculate time until "caught up to height" will execute only if change != 0. This worked for me! I hope it's that simple.
```
if self.old_height is not None:
                change = new_height - self.old_height
                if change is not 0:
                    timestamp_change = new_timestamp - self.old_timestamp
                    total_left = 600000 - new_height
                    time_left = (total_left / change)*timestamp_change
                    humanized = humanize.naturaltime(-time_left)
                    self.system_tray.menu.lnd_status_action.setText(
                        f'ETA: {humanized}, caught up to height {new_height}'
                    )
```

**Comment by bg002h** [comment]
I get same issue on Mac 10.14.3.

**Comment by ando999** [comment]
Thanks for the fix! When will the next release be?
