### ISSUE TITLE
'LndOutputWidget' object has no attribute 'error_message' & [WinError 3] The system cannot find the path specified

### ISSUE THREAD

**Issue by Ape-Cornelius** [lightning-power-users/node-launcher#257]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request

Hi there, I'm currently getting this message on (first) startup with MACOS Mojave.
I also get a similar crash on my Windows, although slightly different (will also post that below.)

Thanks!

* **What is the current behavior?**

MACOS Mojave -
'LndOutputWidget' object has no attribute 'error_message'
File "node_launcher/gui/system_tray_widgets/lnd_output_widget.py", line 151, in handle_unlock_wallet File "node_launcher/gui/system_tray_widgets/lnd_output_widget.py", line 103, in generate_seed 

Windows 10 - 
[WinError 3] The system cannot find the path specified: 'I:\\Bitcoin'
File "run.py", line 22, in File "node_launcher\gui\application.py", line 15, in _init_ File "node_launcher\node_set\node_set.py", line 29, in _init_ File "node_launcher\node_set\bitcoin.py", line 39, in _init_ \

* **If the current behavior is a bug, please provide the steps to reproduce**
On startup every time.

* **What is the expected behavior?**
Crash

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

  - Operating System: [ Windows X | macOS X | Linux ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by sr1919** [comment]
I'm having the same issue on macOS High Sierra 10.13.6

**Comment by PierreRochard** [comment]
Fixed in next release by https://github.com/lightning-power-users/node-launcher/commit/216c8a8a48857f786d438a09ab627b1a2356ef4f
