### ISSUE TITLE
Wild Bug Appeared

### ISSUE THREAD

**Issue by bg002h** [lightning-power-users/node-launcher#260]
* **I'm submitting a ...**
  - [ x] bug report
  - [ ] feature request
  - [ ] support request

* **What is the current behavior?**
If Bitcoin data dir is not available, wild bug appears

* **If the current behavior is a bug, please provide the steps to reproduce**
Have Bitcoin data directory be external drive. Disconnect drive. Open node launcher.

* **What is the expected behavior?**

UI for picking new data dir

* **What is the motivation / use case for changing the behavior?**

avoid crash

* **Please tell us about your environment:**

  - Operating System: [ | macOS | ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Wild bug appears! 
Please copy this text and open an issue on GitHub.
Node Launcher version 6.0.2

Error information:

[Errno 2] No such file or directory: '/Volumes/bitcoin/bitcoin'
File "run.py", line 22, in File "node_launcher/gui/application.py", line 15, in __init__ File "node_launcher/node_set/node_set.py", line 29, in __init__ File "node_launcher/node_set/bitcoin.py", line 39, in __init__

**Comment by PierreRochard** [comment]
Thank you for the bug report! This will be fixed in the next release!
