### ISSUE TITLE
Old testnet bitcoin.conf prevents launch: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by whvandervelde** [lightning-power-users/node-launcher#268]
* **I'm submitting a ...**
  - [ x ] bug report

* **What is the current behavior?**
Node Launcher won't start and will crash with below error message.

```
[Errno 2] No such file or directory: '/Users/somebody/Library/Application Support/Bitcoin/testnet3'
File "run.py", line 22, in File "node_launcher/gui/application.py", line 15, in __init__ File "node_launcher/node_set/node_set.py", line 29, in __init__ File "node_launcher/node_set/bitcoin.py", line 54, in __init__ File "node_launcher/node_set/bitcoin.py", line 128, in get_wallet_paths 
```

* **If the current behavior is a bug, please provide the steps to reproduce**

I had an existing bitcoin testnet installation with a bitcoin.conf for testnet. I removed the testnet data at some point for space and because node wasn't running anyway and this created a problem. When this bitcoin.conf is present in ~/Library/Application Support/Bitcoin the node launcher won't start with above error message. Removing/renaming existing bitcion.conf will allow node launcher to start.

* **What is the expected behavior?**

Node Launcher starting (preferably) and/or perhaps show a hint for the cause of the error and suggest disabling any current bitcoin installation and renaming the bitcoin.conf file.

* **What is the motivation / use case for changing the behavior?**

Not so relevant for this issue, but more robust app launching.

* **Please tell us about your environment:**

  - Operating System: [ macOS ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by PierreRochard** [comment]
Agree, I'll improve error handling on this! Thanks for the thorough bug report!

**Comment by BobleChinois** [comment]
Hi, I want to give it a shot, I've started working on it

**Comment by BobleChinois** [comment]
I was just starting to wrap my head around it, and you push a lot of commits that change everything :laughing: 
If I understood well, there's no support for testnet anymore, so I guess the issue of OP is not relevant anymore?

**Comment by BobleChinois** [comment]
Ok now that's interesting: I happened to already have a `.bitcoin` directory I used to run a regtest sometime ago, and when I launched node-launcher 6.0.5 it seems to have found it and started bitcoind with my regtest bitcoin.conf. Then lnd got stuck because it was trying to connect to bitcoind on mainnet I guess.
Maybe that behaviour is still relevant to OP's issue. Should I open a separate issue?

**Comment by PierreRochard** [comment]
Sorry for all the big changes @BobleChinois! I've got more changes coming for the configuration area as well. I have removed testnet support for now, in the future I'd like to find a way to support regtest/testnet without putting `if` statements all over the codebase
