### ISSUE TITLE
Error information:division by zero line 26

### ISSUE THREAD

**Issue by bitcoinheiros** [lightning-power-users/node-launcher#271]
* **I'm submitting a ...**
  - [x ] bug report

* **What is the current behavior?**
Node Launcher version 6.0.2  
Error information:  division by zero File "node_launcher/gui/system_tray_widgets/output_widget.py", line 26, in handle_output File "node_launcher/gui/system_tray_widgets/lnd_output_widget.py", line 68, in process_output_line 

* **If the current behavior is a bug, please provide the steps to reproduce**
Maybe it happened beaches I used an external hard drive with a pre downloaded blockchain

* **What is the expected behavior?**
looks fine but got this error

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

  - Operating System: [ Windows | macOS | Linux ]
macOS

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by PierreRochard** [comment]
Thank you for reporting this bug! Fix is in https://github.com/lightning-power-users/node-launcher/commit/5cefe073d4a3f5f3ad431f77fadb16448d85e6ac

Let me know if the latest release has another bug or you have a feature request! 

Cheers
