### ISSUE TITLE
Update the Zap Desktop lndconnect link format

### ISSUE THREAD

**Issue by mrfelton** [lightning-power-users/node-launcher#272]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **What is the current behavior?**

Node Launcher is using old-style lndconnect links. Whilst Zap supports these today, it may not in the future.

**old style:**
```
lndconnect:?cert=~/.lnd/tls.cert&macaroon=~/.lnd/admin.macaroon&host=example.com:10009
```
**new style:**
```
lndconnect://example.com:10009?cert=~/.lnd/tls.cert&macaroon=~/.lnd/admin.macaroon
```

The difference is that the `host` portion should now be provided in the `origin` position instead of in the `querystring`

* **What is the expected behavior?**

Node Launcher should open Zap Desktop using latest lndconnect link format.

* **What is the motivation / use case for changing the behavior?**

Ensue that Zap Desktop links continue to work into the future.

**Comment by PierreRochard** [comment]
Thank you @mrfelton!
