### ISSUE TITLE
Wild Bug Appears!

### ISSUE THREAD

**Issue by abentley8** [lightning-power-users/node-launcher#274]
**I'm submitting a ...**
[x ] bug report

**What is the current behavior?**
When I launch Node Launcher, version 6.0.2  , I start syncing my Pruned Node. Around 23% of the way complete, I get this error

_Error information:  division by zero File "node_launcher/gui/system_tray_widgets/output_widget.py", line 26, in handle_output File "node_launcher/gui/system_tray_widgets/lnd_output_widget.py", line 68, in process_output_line_

**If the current behavior is a bug, please provide the steps to reproduce**
I launched Node Launcher and it started syncing a Pruned Bitcoin Node. Around 23% the error (and about 10 hours remaining) above appeared. I also tested restarting my Mac and relaunching my Node Launcher. I have not tested completely erasing and reinstalling Node Launcher from scratch.

What is the expected behavior?
I expected Node Launcher to fully sync my pruned node to 100%

**What is the motivation / use case for changing the behavior?**
I would like to sync a Pruned Node to my Macbook Pro.

**Please tell us about your environment:**
Macbook Pro 13 inch, 2013 macOS 10.14.3 syncing to internal HDD

**Comment by PierreRochard** [comment]
Thank you for the bug report! Hopefully fixed by https://github.com/lightning-power-users/node-launcher/commit/8eac506251892c4220910a428f7f2cb1eb0e5024 in the latest release! 

Let me know if another bug crops up! (or if you have feature requests, those are more fun!)
