### ISSUE TITLE
wild bug 6.0.3

### ISSUE THREAD

**Issue by Freefromchainz** [lightning-power-users/node-launcher#278]
* **I'm submitting a ...**
  - [x ] bug report
  - [ ] feature request
  - [ ] support request

* **What is the current behavior?**
'PySide2.QtWidgets.QMessageBox' called with wrong argument types: PySide2.QtWidgets.QMessageBox(Application) Supported signatures: PySide2.QtWidgets.QMessageBox(PySide2.QtWidgets.QMessageBox.Icon, unicode, unicode, PySide2.QtWidgets.QMessageBox.StandardButtons = QMessageBox.NoButton, PySide2.QtWidgets.QWidget = nullptr, PySide2.QtCore.Qt.WindowFlags = Qt.Dialog | Qt.MSWindowsFixedSizeDialogHint) PySide2.QtWidgets.QMessageBox(PySide2.QtWidgets.QWidget = nullptr)
File "node_launcher\gui\application.py", line 64, in check_version 

* **If the current behavior is a bug, please provide the steps to reproduce**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

  - Operating System: [ Windows | macOS | Linux ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by abentley8** [comment]
Same bug occurring on my Macbook Pro 10.14.3 while I am trying to sync my pruned node (85% complete)

I am ignoring the popup and it looks like my Pruned Node is still syncing and the percentage is going up.

**Comment by PierreRochard** [comment]
Thank you for reporting this bug! I'll upload a fixed version asap
