### ISSUE TITLE
Wild bug appears!  

### ISSUE THREAD

**Issue by pbnkb** [lightning-power-users/node-launcher#280]
* **I'm submitting a ...**
  - [x ] bug report
  - [ ] feature request
  - [ ] support request

* **What is the current behavior?**

Node Launcher version 6.0.2  Error information:  'PySide2.QtWidgets.QMessageBox' called with wrong argument types: PySide2.QtWidgets.QMessageBox(Application) Supported signatures: PySide2.QtWidgets.QMessageBox(PySide2.QtWidgets.QMessageBox.Icon, unicode, unicode, PySide2.QtWidgets.QMessageBox.StandardButtons = QMessageBox.NoButton, PySide2.QtWidgets.QWidget = nullptr, PySide2.QtCore.Qt.WindowFlags = Qt.Dialog | Qt.MSWindowsFixedSizeDialogHint) PySide2.QtWidgets.QMessageBox(PySide2.QtWidgets.QWidget = nullptr) File "node_launcher\gui\application.py", line 64, in check_version  

Node Launcher version 6.0.2 Wild bug appears!  
Error information:  Internal C++ object (PySide2.QtCore.QProcess) already deleted. File "node_launcher\gui\system_tray_widgets\output_widget.py", line 22, in handle_output 

* **If the current behavior is a bug, please provide the steps to reproduce**

open node launcher

* **What is the expected behavior?**

open and sync

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

  - Operating System:  Windows 10 pro

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by robbie2121** [comment]
i'm getting the same thing out of the blue!

'PySide2.QtWidgets.QMessageBox' called with wrong argument types: PySide2.QtWidgets.QMessageBox(Application) Supported signatures: PySide2.QtWidgets.QMessageBox(PySide2.QtWidgets.QMessageBox.Icon, unicode, unicode, PySide2.QtWidgets.QMessageBox.StandardButtons = QMessageBox.NoButton, PySide2.QtWidgets.QWidget = nullptr, PySide2.QtCore.Qt.WindowFlags = Qt.Dialog | Qt.MSWindowsFixedSizeDialogHint) PySide2.QtWidgets.QMessageBox(PySide2.QtWidgets.QWidget = nullptr)
File "node_launcher\gui\application.py", line 64, in check_version

**Comment by cryptomulde** [comment]
Wild bug appears! 
Please copy this text and open an issue on GitHub.
Node Launcher version 6.0.2

Error information:

'PySide2.QtWidgets.QMessageBox' called with wrong argument types: PySide2.QtWidgets.QMessageBox(Application) Supported signatures: PySide2.QtWidgets.QMessageBox(PySide2.QtWidgets.QMessageBox.Icon, str, str, PySide2.QtWidgets.QMessageBox.StandardButtons = PySide2.QtWidgets.QMessageBox.StandardButton.NoButton, PySide2.QtWidgets.QWidget = None, PySide2.QtCore.Qt.WindowFlags = Instance(Qt.Dialog | Qt.MSWindowsFixedSizeDialogHint)) PySide2.QtWidgets.QMessageBox(PySide2.QtWidgets.QWidget = None)
File "node_launcher/gui/application.py", line 64, in check_version 


same here. yesterday was using it just fine

**Comment by i22ie** [comment]
Same issue as above.
Windows 10

**Comment by cryptomulde** [comment]
getting it on win10 and macOS

**Comment by robbie2121** [comment]
getting on both my windows 10 machines.

**Comment by PierreRochard** [comment]
Sorry folks! I forgot to bump the version number and the update dialog had a bug in it! New release should fix that up.
