### ISSUE TITLE
Error message when trying to install on Windows 10

### ISSUE THREAD

**Issue by notfreedude** [lightning-power-users/node-launcher#286]
* **I'm submitting a ...**
  - [x ] bug report
  - [ ] feature request
  - [ ] support request

Node Launcher version 6.0.2

Error information:

'PySide2.QtWidgets.QMessageBox' called with wrong argument types: PySide2.QtWidgets.QMessageBox(Application) Supported signatures: PySide2.QtWidgets.QMessageBox(PySide2.QtWidgets.QMessageBox.Icon, str, str, PySide2.QtWidgets.QMessageBox.StandardButtons = PySide2.QtWidgets.QMessageBox.StandardButton.NoButton, PySide2.QtWidgets.QWidget = None, PySide2.QtCore.Qt.WindowFlags = Instance(Qt.Dialog | Qt.MSWindowsFixedSizeDialogHint)) PySide2.QtWidgets.QMessageBox(PySide2.QtWidgets.QWidget = None)
File "node_launcher\gui\application.py", line 64, in check_version

**Comment by PierreRochard** [comment]
Should work in the newest release: https://github.com/lightning-power-users/node-launcher/releases

Let me know if it doesn't and I'll reopen the issue!
