### ISSUE TITLE
Can't get password from keychain

### ISSUE THREAD

**Issue by bitcoinheiros** [lightning-power-users/node-launcher#292]
* **I'm submitting a ...**
  - [x ] bug report
  - [ ] feature request
  - [ ] support request

* **What is the current behavior?**
node not launching

* **If the current behavior is a bug, please provide the steps to reproduce**
just trying to launch it

* **What is the expected behavior?**
launch the node

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
macOS
  - Operating System: [ Windows | macOS | Linux ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
Can't get password from keychain: (-25293, 'Security Auth Failure: make sure python is signed with codesign util')
File "node_launcher/gui/system_tray_widgets/lnd_output_widget.py", line 179, in auto_unlock_wallet File "keyring/backends/OS_X.py", line 59, in get_password

**Comment by cooperkernan** [comment]
Try resetting keychain access? https://teamtreehouse.com/community/keychain-access-i-hit-deny-on-keychain-access-and-now-it-keeps-saying-build-failed-how-do-i-reset-my-keychain

**Comment by cooperkernan** [comment]
Did that work? @bitcoinheiros

**Comment by bitcoinheiros** [comment]
Sorry for the delay. Looks like there was a conflict with another node I run in my computer and after a reboot it worked fine. Thanks for the support
