### ISSUE TITLE
Wild bug appears - version 6.0.2 - Windows 10

### ISSUE THREAD

**Issue by hodlonaut** [lightning-power-users/node-launcher#293]
'PySide2.QtWidgets.QMessageBox' called with wrong argument types: PySide2.QtWidgets.QMessageBox(Application) Supported signatures: PySide2.QtWidgets.QMessageBox(PySide2.QtWidgets.QMessageBox.Icon, unicode, unicode, PySide2.QtWidgets.QMessageBox.StandardButtons = QMessageBox.NoButton, PySide2.QtWidgets.QWidget = nullptr, PySide2.QtCore.Qt.WindowFlags = Qt.Dialog | Qt.MSWindowsFixedSizeDialogHint) PySide2.QtWidgets.QMessageBox(PySide2.QtWidgets.QWidget = nullptr)
File "node_launcher\gui\application.py", line 64, in check_version

**Comment by PierreRochard** [comment]
Fixed in the latest release!

**Comment by PierreRochard** [comment]
Let me know if it’s still a problem or if you have feature ideas!
