### ISSUE TITLE
 Wild bug appears!

### ISSUE THREAD

**Issue by iulian31** [lightning-power-users/node-launcher#294]
Hi all, 

I opened today my node launcher and got this beautiful message.

I'm beginner and i don't really know what this means. 

Wild bug appears! 
Please copy this text and open an issue on GitHub.
Node Launcher version 6.0.2

Error information:

'PySide2.QtWidgets.QMessageBox' called with wrong argument types: PySide2.QtWidgets.QMessageBox(Application) Supported signatures: PySide2.QtWidgets.QMessageBox(PySide2.QtWidgets.QMessageBox.Icon, str, str, PySide2.QtWidgets.QMessageBox.StandardButtons = PySide2.QtWidgets.QMessageBox.StandardButton.NoButton, PySide2.QtWidgets.QWidget = None, PySide2.QtCore.Qt.WindowFlags = Instance(Qt.Dialog | Qt.MSWindowsFixedSizeDialogHint)) PySide2.QtWidgets.QMessageBox(PySide2.QtWidgets.QWidget = None)
File "node_launcher\gui\application.py", line 64, in check_version 

The operating system is windows 10.

**Comment by PierreRochard** [comment]
This should be fixed in the latest release, I'll reopen if it's not!

**Comment by iulian31** [comment]
Hi Pierre,

I downloaded the below version 

![image](https://user-images.githubusercontent.com/46089593/56273106-25e8e580-610d-11e9-9a45-980bf2cbe348.png)

After executing the file same error appeared 

![debug](https://user-images.githubusercontent.com/46089593/56273524-ee2e6d80-610d-11e9-8c4f-b63a2c1f366b.JPG)


![cmd screen 1](https://user-images.githubusercontent.com/46089593/56273535-f2f32180-610d-11e9-9ec1-75e145f7ef09.jpg)

![cmd screen 2](https://user-images.githubusercontent.com/46089593/56273545-f7b7d580-610d-11e9-9c86-c6635becdace.JPG)

Please advise.

Thank you.

**Comment by iulian31** [comment]
This is new

![image](https://user-images.githubusercontent.com/46089593/56274464-cfc97180-610f-11e9-8e8d-c8c2642668fe.png)

Thank you

**Comment by PierreRochard** [comment]
The latest release is 6.0.5, please try that one! If there is a problem with it, let’s debug it (please do not use old versions of the Node Launcher)
