### ISSUE TITLE
Launch error

### ISSUE THREAD

**Issue by CoreyB216** [lightning-power-users/node-launcher#305]
* **I'm submitting a ...**
  - [x] bug report

* **What is the current behavior?**
Node Launcher won't open. 

* **If the current behavior is a bug, please provide the steps to reproduce**
Any time I try to launch it gives me an error message. 

Error information:

'PySide2.QtWidgets.QMessageBox' called with wrong argument types: PySide2.QtWidgets.QMessageBox(Application) Supported signatures: PySide2.QtWidgets.QMessageBox(PySide2.QtWidgets.QMessageBox.Icon, str, str, PySide2.QtWidgets.QMessageBox.StandardButtons = PySide2.QtWidgets.QMessageBox.StandardButton.NoButton, PySide2.QtWidgets.QWidget = None, PySide2.QtCore.Qt.WindowFlags = Instance(Qt.Dialog | Qt.MSWindowsFixedSizeDialogHint)) PySide2.QtWidgets.QMessageBox(PySide2.QtWidgets.QWidget = None)
File "node_launcher/gui/application.py", line 64, in check_version 

* **What is the expected behavior?**
Normal application launch

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

  - Operating System: [  macOS  ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Was still in blockchain download phase at about 77%. Block download time had slowed immensely so I quit and wanted to reopen to see if that would have any effect. I am running the node launcher and storing blockchain on an external drive connected to my mac.

**Comment by PierreRochard** [comment]
Which version of the Node Launcher are you using?

**Comment by CoreyB216** [comment]
> Which version of the Node Launcher are you using?
6.0.2 
Sorry, just realized I should have kept that in the error report

**Comment by mdotbit** [comment]
Same thing for my in 6.0.2

**Comment by CoreyB216** [comment]
Issue resolved itself after updating to 6.0.4.

**Comment by PierreRochard** [comment]
Thanks for reporting it @CoreyB216 !
