### ISSUE TITLE
New Setup Process has no seeds or passwords?

### ISSUE THREAD

**Issue by robbie2121** [lightning-power-users/node-launcher#307]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [ x] support request

* **What is the current behavior?**
Before when I started node launcher for the first time and setup, it would ask me to write down LND seed, LND password and mnemonic seed pw. As well as ZAP wallet seed and password.

New Node Launcher didn't require me to do any of this, so I have no seeds or passwords.

Is this intended? Or did I miss something somehow. Maybe I should re-do the process and check again.

* **If the current behavior is a bug, please provide the steps to reproduce**
Setup node launcher 6.0.4 from scratch

* **What is the expected behavior?**
Should give me seeds for LND and ZAP and create passwords.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

  - Operating System: Windows 10 64 bit
  - node launcher 6.0.4
  - lnd v0.6-beta-rc4

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by PierreRochard** [comment]
> Is this intended? 

Yes, it is intended, seed and passwords are automatically generated and stored in your system keychain.
