### ISSUE TITLE
lnd.conf:1: malformed key=value (ration File)

### ISSUE THREAD

**Issue by JuStAguY2** [lightning-power-users/node-launcher#319]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **What is the current behavior?**
I am getting a: lnd.conf:1: malformed key=value (ration File)
message in the LND-Console

* **If the current behavior is a bug, please provide the steps to reproduce**

Happened after Update to the Node Launcher version 5.4.1 

What should be written in the lnd.conf file between those two lines: 

listen=xxx.x.x.x:xxxx 

rpclisten=xxx.x.x.x:xxxxx 
It´s the only line without an assignment...

* **Please tell us about your environment:**
  - Operating System: [ Windows, NodeLauncher Version 5.4.1]
* **Other information** 
I guess, the lnd.conf file was somehow compromised during the update of the node launcher. I never manually modified the file.

**Comment by runjam1** [comment]
I guess support is sparse.

**Comment by runjam1** [comment]
Pierre must be very busy.

**Comment by PierreRochard** [comment]
@JuStAguY2 try moving your lnd.conf file and downloading the latest release: https://github.com/lightning-power-users/node-launcher/releases
The lnd.conf file will be regenerated

**Comment by JuStAguY2** [comment]
Worked! Thx for the reply!
