### ISSUE TITLE
Bitcoin core

### ISSUE THREAD

**Issue by rico1881** [lightning-power-users/node-launcher#332]
Hi there i am running a full node and not that technical unfortunately, to install the node launcher will it just sync with the full
Node I already have? 
Thanks 

* **If the current behavior is a bug, please provide the steps to reproduce**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

  - Operating System: [ Windows | macOS | Linux ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by PierreRochard** [comment]
Correct, under the hood the Node Launcher uses Bitcoin Core with the same default data directory
