### ISSUE TITLE
6.0.5 Wild Bug appears!

### ISSUE THREAD

**Issue by jmann6** [lightning-power-users/node-launcher#343]
* **I'm submitting a ...**
  - [ X ] bug report
  - [ ] feature request
  - [ ] support request

* **What is the current behavior?**
When I click the Windows.Node.Launcher the Wild Bug modal appears.  
![6 0 5 wild bug](https://user-images.githubusercontent.com/3744618/57571512-93b2c500-73cc-11e9-8cb0-c3ce20b5c5d0.PNG)

* **If the current behavior is a bug, please provide the steps to reproduce**
Download 6.05.  and click Windows.Node.Launcher

* **What is the expected behavior?**
Sync

* **What is the motivation / use case for changing the behavior?**
Upgrade

* **Please tell us about your environment:**

  - Operating System: [ Windows | macOS | Linux ]

Windows 10 English Home

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by PierreRochard** [comment]
What's in your lnd.conf? `%localappdata%/Lnd/lnd.conf`

**Comment by jmann6** [comment]
I x'd out first part because still learning how lightning works ⚡️ 

listen=xxx.x.x.x:9745

_user

listen=xxx.x.x.x:9790

bitcoind.zmqpubrawblock=tcp://xxx.x.x.x:18502

bitcoind.zmqpubrawtx=tcp://xxx.x.x.x:18503

**Comment by PierreRochard** [comment]
I would recommending, closing the Node Launcher, deleting the lnd.conf, to allow the Node Launcher to automatically regenerate a new one

**Comment by jmann6** [comment]
Thanks @PierreRochard!  That helped!  Actually seeing LND output now.

**Comment by PierreRochard** [comment]
Will reopen if it's a problem again!
