### ISSUE TITLE
How to re-launch node-launcher after a reboot (Windows)

### ISSUE THREAD

**Issue by sixside** [lightning-power-users/node-launcher#393]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [X] support request

* **What is the current behavior?**
Installed v6.0.6 on Windows. Was running just fine, had to reboot Windows for some updates and now I can't seem to find/run node-launcher again. I see the new directory \AppData\Local\Node Launcher and the sub-directories for \bitcoin & \lnd and I can run the bitcoin-qt.exe just fine. But I can't seem to figure out how to re-launch node-launcher that runs both bitcoin & lightning nodes simultaneously as it was originally running before the reboot (as shown in this screenshot: 
https://raw.githubusercontent.com/PierreRochard/node-launcher/master/windows.png

I tried looking for what seems to be the relevant python files (node_launcher/gui/*.py etc) on my system but nothing turns up. 

Any help on how to get back to the default state would be appreciated! In the meantime, I'm running the included Bitcoin Core client to continue syncing blocks.

* **If the current behavior is a bug, please provide the steps to reproduce**

* **What is the expected behavior?**
I expect to find an obvious "click me" file or icon somewhere to re-establish the default node-launcher state as shown in the screenshot.
https://raw.githubusercontent.com/PierreRochard/node-launcher/master/windows.png

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

  - Operating System: [ Windows ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by sixside** [comment]
My "fix" was just to re-run the downloaded .exe file, but I'm not sure if this is the intended behavior of Node Launcher. 

FWIW, my expectation was that once I ran the exe the first time it would install the necessary scripts/files so that each time I boot up my computer it auto-launches Node Launcher (and BTC/LND nodes by proxy). Since that doesn't seem to be the case, re-running the exe does seem to fix the issue, and is a satisfactory solution.

**Comment by PierreRochard** [comment]
I definitely agree that there should be a Setup.exe that install the binary and puts a short cut in the start menu
