### ISSUE TITLE
Node Launcher not launching.

### ISSUE THREAD

**Issue by shineon137** [lightning-power-users/node-launcher#466]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [ x] support request

* **What is the current behavior?**
I click on the Node Launcher program and nothing happens. :(

* **If the current behavior is a bug, please provide the steps to reproduce**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
macOS 10.11.6, Processor 2.26 GHz Intel Core 2 Duo, RAM 8 GB 1067 MHz DDR3
  - Operating System: [ Windows | macOS | Linux ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by PierreRochard** [comment]
Hi @shineon137 , you need at least macOS 10.14.6 (Mojave) for the latest release to work: https://github.com/lightning-power-users/node-launcher/releases
