### ISSUE TITLE
Bug: Runaway exception

### ISSUE THREAD

**Issue by otech47** [lightning-power-users/node-launcher#70]
Windows 10

![screenshot_21](https://user-images.githubusercontent.com/4914611/50198282-e5bd5600-0318-11e9-9cae-3092ebabdd39.png)

I clicked Launch Bitcoin, Bitcoin Core started booting but within 5-10 seconds this error appears

I expected my node to boot as usual and eventually see the Bitcoin Core Wallet UI. I am able to exit Node Launcher and boot up Bitcoin Core without a problem.

Also if I try opening Node Launcher while my node is running I get another error but can make a separate issue for that

Specs:
![screenshot_23](https://user-images.githubusercontent.com/4914611/50198424-9166a600-0319-11e9-8496-4e0b88b3e3ce.png)
![screenshot_24](https://user-images.githubusercontent.com/4914611/50198425-9166a600-0319-11e9-85ee-743a93802146.png)

**Comment by PierreRochard** [comment]
Yikes, I haven't seen that before, I'll leave it open and see if others experience the same issue / workarounds they found

**Comment by ionbtz** [comment]
I had the same problem. Probably an error on my external hdd. Redownloaded  the blockchain on my pc (ssd)

**Comment by otech47** [comment]
@ionbtz interesting comment. I have the blockchain downloaded to a separate volume but on the same ssd as the OS. Maybe that's a lead to investigate

**Comment by PierreRochard** [comment]
@otech47 anything new on this? Closing for now, I haven't had more bug reports about this
