### ISSUE TITLE
Error message is whited out on macos dark

### ISSUE THREAD

**Issue by BrianSipple** [lightning-power-users/node-launcher#74]
I downloaded and unzipped 5.3.0, moved it to my Applications directory, and then attempted to run it (initially accepting Apple's permission prompt). 

Unfortunately, all I get is a dialog showing a blank text box:

<img width="798" alt="screen shot 2018-12-19 at 11 51 38 pm" src="https://user-images.githubusercontent.com/5483853/50264735-effb5500-03e9-11e9-94fa-2571dc5eca2b.png">

When I click "Ok", the application closes. Restarting produces the same result, so I'm not really sure where to go from here or what the cause might be.

**Comment by BrianSipple** [comment]
Additional note: this happens with or without `bitcoind` running during start-up.

**Comment by BrianSipple** [comment]
Ha, so I was able get the app running after stopping `bitcoind`. I can see why that might cause issues 😄.   

@PierreRochard Perhaps there could still be some refactoring around whatever's generating the error message/dialog? I'll close this particular issue, though.

**Comment by PierreRochard** [comment]
@BrianSipple yikes, I've had this as well, there actually should be a message in the prompt but the font is white due to the dark macos theme. I'll see how to fix that!

**Comment by PierreRochard** [comment]
This also affects the mnemonic seed

**Comment by stalcottsmith** [comment]
Yes, I was going to post that even printing the mnemonic seed does not work in dark mode UI.  However, you can see the characters if you select them to highlight.

**Comment by BobleChinois** [comment]
It seems that Bitcoin Core encountered a similar issue with 17.0, and they fixed it like this: https://github.com/bitcoin/bitcoin/pull/14593
According to my understanding, the same fix on node launcher would simply add `NSRequiresAquaSystemAppearance=True` in `run-mac.spec`
If this is correct, I can make the PR.

**Comment by PierreRochard** [comment]
@BobleChinois yup that looks like the fix! Thank you!
